### ISSUE TITLE
Circular timer loading bar is loaded out of the container by placing the mouse on the "pomodoro" button

### ISSUE THREAD

**Issue by ludovicobesana** [zynth17/pomodoro-app#1]
### Step by step

- I go to this website: https://pomodoro-app-zynth17.vercel.app/
- I place the mouse on the "pomodoro" button
- I reload the page having the mouse placed on "pomodoro" button

### Expected Result
I expect to see the circular timer inside the container

### Current Result

Circular timer loading bar is loaded out of the container by placing the mouse on the "pomodoro" button

https://user-images.githubusercontent.com/35035423/121754416-dfd51400-cb14-11eb-989d-06f779e18a72.mp4

**Comment by hi-reeve** [comment]
hey thankyou for the feedback, i cannot really re produce the issue, on my browser it does not have this problem

**Comment by ludovicobesana** [comment]
> hey thankyou for the feedback, i cannot really re produce the issue, on my browser it does not have this problem

You're welcome!
I used Chrome as a browser 👍

**Comment by hi-reeve** [comment]
fixed [6cc555b](https://github.com/zynth17/pomodoro-app/commit/6cc555bc389405ccf7c51a53d8408264040784bd)
